// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArhM9HBSW0qDloLhZUs_oCXvtVwoQ_Pj8',
    appId: '1:780168377071:web:66e978f927ba927d8c211a',
    messagingSenderId: '780168377071',
    projectId: 'smart-student-b52ff',
    authDomain: 'smart-student-b52ff.firebaseapp.com',
    storageBucket: 'smart-student-b52ff.firebasestorage.app',
    measurementId: 'G-SBT78E48H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3iq7_XsWxKxck15LettMAWed3EuuUBdc',
    appId: '1:780168377071:android:687bfbec8932897f8c211a',
    messagingSenderId: '780168377071',
    projectId: 'smart-student-b52ff',
    storageBucket: 'smart-student-b52ff.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGkpK8MeeqLe52r1NDzpXx5QVt1IrAcFs',
    appId: '1:780168377071:ios:47f1c7cbf76dd9f68c211a',
    messagingSenderId: '780168377071',
    projectId: 'smart-student-b52ff',
    storageBucket: 'smart-student-b52ff.firebasestorage.app',
    iosClientId: '780168377071-3fm1e9oq8n8is0p6gcm3f5vbopf8bkaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartStudent',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGkpK8MeeqLe52r1NDzpXx5QVt1IrAcFs',
    appId: '1:780168377071:ios:47f1c7cbf76dd9f68c211a',
    messagingSenderId: '780168377071',
    projectId: 'smart-student-b52ff',
    storageBucket: 'smart-student-b52ff.firebasestorage.app',
    iosClientId: '780168377071-3fm1e9oq8n8is0p6gcm3f5vbopf8bkaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArhM9HBSW0qDloLhZUs_oCXvtVwoQ_Pj8',
    appId: '1:780168377071:web:3a5f19b9e0b315858c211a',
    messagingSenderId: '780168377071',
    projectId: 'smart-student-b52ff',
    authDomain: 'smart-student-b52ff.firebaseapp.com',
    storageBucket: 'smart-student-b52ff.firebasestorage.app',
    measurementId: 'G-7R5SD6DLSW',
  );
}
